Vagrant.configure("2") do |config|

  required_plugins = ["vagrant-hostsupdater"]
  config.vm.box = "ubuntu/xenial64"
  config.vm.network "private_network", ip: "192.168.10.100"
  config.hostsupdater.aliases = ["development.local"]

  # synced folder -- connection both ways
  # How to send code to VM
  # config.vm.synced_folder("path_to_origin_folder_to_sync", "path_in_machine_to_create_synced_folder)
  config.vm.synced_folder("app", "/app")


  config.vm.provision "shell", path: "environment/provision.sh"
end
